# Generated by Django 2.1.4 on 2018-12-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20181227_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Programmer'), (2, 'Medicine'), (3, 'OfficeManager'), (4, 'Military')], default=1, help_text='Выберите категорию'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'isEmployer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='graphic',
            field=models.IntegerField(blank=True, choices=[(1, 'FullDay'), (2, 'PartDay')], default=1, help_text='Выберите график работы'),
        ),
    ]
