# Generated by Django 2.1.4 on 2018-12-27 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_auto_20181227_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'isEmployer': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ban',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'isEmployer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'isEmployer': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Models.Job'),
        ),
    ]
